---
# tasks file for mysql exporter
 
- name: Clone the code repository
  git: repo=https://github.com/prometheus/mysqld_exporter.git update=yes version=master dest={{ mysql_exporter_clone_path }} accept_hostkey=True


- stat:
    path: {{ mysql_exporter_clone_path }}/mysqld_exporter
  register: built

- name: make it
  command: make
  args:
    chdir: {{ mysql_exporter_clone_path }}
  when: built.stat.exists == False
  notify: start mysql exporter