---
# tasks file for mysql exporter


- name: monitoring mysql directory
  file: path='{{ root_monitoring_mysql }}' state=directory

- name: Pull the lateste version
  command: docker pull prom/mysqld-exporter

- name: copy the docker-compose file
  action: >
    template src=docker-compose-mysql.yml.j2 dest={{root_monitoring_mysql}}/docker-compose.yml
    mode=0644 owner=root group=root
  notify:
    - start mysql exporter
