---
# handlers file for rahal.prometheus-exporters

- name: reload nginx
  service: name=nginx state=reloaded
  when: (nginx_is_service == True)


# start exporter mysql
- name: start mysql exporter
  docker_service:
    project_src: "{{ root_monitoring_mysql }}"
    project_name: "prom_exporter_{{ item.name }}"
  environment:
      PORT: "{{ item.prom_port }}"
      MYSQL_CONTAINER: "{{ item.name }}"
      DATA_SOURCE_NAME: "{{ item.user }}:{{ item.pass }}@tcp(bdd:{{ item.port }})/"
      NETWORK_MODE: "{{ item.network }}"
  with_items: "{{ mysql_containers }}"


# start exporter php
- name: start php exporter
  docker_service:
    project_src: "{{ root_monitoring_php }}"
    project_name: "php_exporter_{{ item.name }}"
  environment:
      PORT: "{{ item.prom_port }}"
      PHP_CONTAINER: "{{ item.name }}"
      FASTCGI_URL: "tcp://{{ item.name }}:{{ item.port }}/status"
      NETWORK_MODE: "{{ item.network }}"
  with_items: "{{ php_containers }}"


# start memcached exporter
- name: start memcached exporter
  docker_service:
    project_src: "{{ root_monitoring_memcached }}"
    project_name: "mmc_exporter_{{ item.name }}"
  environment:
      PORT: "{{ item.prom_port }}"
      MEMCACHED_CONTAINER: "{{ item.name }}"
      FASTCGI_URL: "tcp://{{ item.name }}:{{ item.port }}/status"
      NETWORK_MODE: "{{ item.network }}"
  with_items: "{{ memcached_containers }}"

